### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by Julyandsummer** [zonghaofan/noise2noise#2]
Noise2Noise: Learning Image Restoration without Clean Data (Lethinen et al., 2018)
Training parameters: 
  Train dir = ./red_detection/noise2noise/data/train
  Valid dir = ./red_detection/noise2noise/data/val
  W = ./red_detection/noise2noise/src/water_imgs
  Ckpt save path = ./red_detection/noise2noise/ckpts
  Pretrain model path = ./red_detection/noise2noise/ckpts/text-0753/n2n-epoch7-0.00266.pth
  Ckpt overwrite = False
  Report interval = 500
  Train size = None
  Valid size = None
  Learning rate = 0.001
  Adam = [0.9, 0.99, 1e-08]
  Batch size = 4
  Nb epochs = 30
  Loss = l0
  Cuda = False
  Plot stats = False
  Noise type = text
  Noise param = 0.5
  Seed = None
  Crop size = 0
  Resize size = 640
  Num workers = 0
  Clean targets = False

EPOCH 1 / 30
Traceback (most recent call last):
  File "D:/noise2noise-main/train_fzh.py", line 88, in <module>
    main()
  File "D:/noise2noise-main/train_fzh.py", line 59, in main
    n2n.train(train_loader, valid_loader)
  File "D:\noise2noise-main\noise2noise_fzh.py", line 262, in train
    for batch_idx, (source, target) in enumerate(train_loader):
  File "D:\py\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\py\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\py\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\py\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\noise2noise-main\datasets.py", line 335, in __getitem__
    img, resize_ori_img = self._add_text_way_one(img_ori)
  File "D:\noise2noise-main\datasets.py", line 221, in _add_text_way_one
    font = ImageFont.truetype(serif, random.randint(h // 8, h // 6))
  File "D:\py\lib\site-packages\PIL\ImageFont.py", line 836, in truetype
    return freetype(font)
  File "D:\py\lib\site-packages\PIL\ImageFont.py", line 833, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\py\lib\site-packages\PIL\ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
请问一下您，在目录里是存在训练的资源，为什么会出现这种情况呢？是因为训练集做了一些处理吗？

**Comment by fanpeace** [comment]
> Noise2Noise: Learning Image Restoration without Clean Data (Lethinen et al., 2018)
> Training parameters:
> Train dir = ./red_detection/noise2noise/data/train
> Valid dir = ./red_detection/noise2noise/data/val
> W = ./red_detection/noise2noise/src/water_imgs
> Ckpt save path = ./red_detection/noise2noise/ckpts
> Pretrain model path = ./red_detection/noise2noise/ckpts/text-0753/n2n-epoch7-0.00266.pth
> Ckpt overwrite = False
> Report interval = 500
> Train size = None
> Valid size = None
> Learning rate = 0.001
> Adam = [0.9, 0.99, 1e-08]
> Batch size = 4
> Nb epochs = 30
> Loss = l0
> Cuda = False
> Plot stats = False
> Noise type = text
> Noise param = 0.5
> Seed = None
> Crop size = 0
> Resize size = 640
> Num workers = 0
> Clean targets = False
> 
> EPOCH 1 / 30
> Traceback (most recent call last):
> File "D:/noise2noise-main/train_fzh.py", line 88, in
> main()
> File "D:/noise2noise-main/train_fzh.py", line 59, in main
> n2n.train(train_loader, valid_loader)
> File "D:\noise2noise-main\noise2noise_fzh.py", line 262, in train
> for batch_idx, (source, target) in enumerate(train_loader):
> File "D:\py\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> data = self._next_data()
> File "D:\py\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> File "D:\py\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "D:\py\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "D:\noise2noise-main\datasets.py", line 335, in **getitem**
> img, resize_ori_img = self._add_text_way_one(img_ori)
> File "D:\noise2noise-main\datasets.py", line 221, in _add_text_way_one
> font = ImageFont.truetype(serif, random.randint(h // 8, h // 6))
> File "D:\py\lib\site-packages\PIL\ImageFont.py", line 836, in truetype
> return freetype(font)
> File "D:\py\lib\site-packages\PIL\ImageFont.py", line 833, in freetype
> return FreeTypeFont(font, size, index, encoding, layout_engine)
> File "D:\py\lib\site-packages\PIL\ImageFont.py", line 194, in **init**
> font, size, index, encoding, layout_engine=layout_engine
> OSError: cannot open resource
> 请问一下您，在目录里是存在训练的资源，为什么会出现这种情况呢？是因为训练集做了一些处理吗？

这个目录是我的,你需要换成你自己的

**Comment by Julyandsummer** [comment]
> > Noise2Noise: Learning Image Restoration without Clean Data (Lethinen et al., 2018)
> > Training parameters:
> > Train dir = ./red_detection/noise2noise/data/train
> > Valid dir = ./red_detection/noise2noise/data/val
> > W = ./red_detection/noise2noise/src/water_imgs
> > Ckpt save path = ./red_detection/noise2noise/ckpts
> > Pretrain model path = ./red_detection/noise2noise/ckpts/text-0753/n2n-epoch7-0.00266.pth
> > Ckpt overwrite = False
> > Report interval = 500
> > Train size = None
> > Valid size = None
> > Learning rate = 0.001
> > Adam = [0.9, 0.99, 1e-08]
> > Batch size = 4
> > Nb epochs = 30
> > Loss = l0
> > Cuda = False
> > Plot stats = False
> > Noise type = text
> > Noise param = 0.5
> > Seed = None
> > Crop size = 0
> > Resize size = 640
> > Num workers = 0
> > Clean targets = False
> > EPOCH 1 / 30
> > Traceback (most recent call last):
> > File "D:/noise2noise-main/train_fzh.py", line 88, in
> > main()
> > File "D:/noise2noise-main/train_fzh.py", line 59, in main
> > n2n.train(train_loader, valid_loader)
> > File "D:\noise2noise-main\noise2noise_fzh.py", line 262, in train
> > for batch_idx, (source, target) in enumerate(train_loader):
> > File "D:\py\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> > data = self._next_data()
> > File "D:\py\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> > data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> > File "D:\py\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "D:\py\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "D:\noise2noise-main\datasets.py", line 335, in **getitem**
> > img, resize_ori_img = self._add_text_way_one(img_ori)
> > File "D:\noise2noise-main\datasets.py", line 221, in _add_text_way_one
> > font = ImageFont.truetype(serif, random.randint(h // 8, h // 6))
> > File "D:\py\lib\site-packages\PIL\ImageFont.py", line 836, in truetype
> > return freetype(font)
> > File "D:\py\lib\site-packages\PIL\ImageFont.py", line 833, in freetype
> > return FreeTypeFont(font, size, index, encoding, layout_engine)
> > File "D:\py\lib\site-packages\PIL\ImageFont.py", line 194, in **init**
> > font, size, index, encoding, layout_engine=layout_engine
> > OSError: cannot open resource
> > 请问一下您，在目录里是存在训练的资源，为什么会出现这种情况呢？是因为训练集做了一些处理吗？
> 
> 这个目录是我的,你需要换成你自己的

傻了……好尴尬……谢谢！我直接换了就行了……
