### ISSUE TITLE
我是刚学pytorch的想问一下和TensorFlow调用函数方法一样吗

### ISSUE THREAD

**Issue by shine-233** [zonghaofan/noise2noise#3]
就是训练模型直接python train.py --image_dir dataset/train --test_dir dataset/test --image_size 128 --batch_size 8 --lr 0.001 --source_noise_model text,0,50 --target_noise_model text,0,50 --val_noise_model text,25,25 --loss mae --output_path text_noise
就行了

**Comment by Ceiso1** [comment]
@shine-233 @zonghaofan 
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from keras.callbacks import LearningRateScheduler, ModelCheckpoint
  File "D:\Miniconda\lib\site-packages\keras\__init__.py", line 21, in <module>
    from tensorflow.python import tf2
ImportError: cannot import name 'tf2'

输完训练模型代码就卡在这个tf2这里 求指点

**Comment by fanpeace** [comment]
> @shine-233 @zonghaofan Traceback (most recent call last): File "train.py", line 4, in from keras.callbacks import LearningRateScheduler, ModelCheckpoint File "D:\Miniconda\lib\site-packages\keras__init__.py", line 21, in from tensorflow.python import tf2 ImportError: cannot import name 'tf2'
> 
> 输完训练模型代码就卡在这个tf2这里 求指点

没有你说的这行代码啊，这是pytorch没有tf

**Comment by Ceiso1** [comment]
> > @shine-233 @zonghaofan Traceback (most recent call last): File "train.py", line 4, in from keras.callbacks import LearningRateScheduler, ModelCheckpoint File "D:\Miniconda\lib\site-packages\keras__init__.py", line 21, in from tensorflow.python import tf2 ImportError: cannot import name 'tf2'
> > 输完训练模型代码就卡在这个tf2这里 求指点
> 
> 没有你说的这行代码啊，这是pytorch没有tf

https://github.com/zxq2233/n2n-watermark-remove
其实是这个项目的 小白跟着保姆级教程走的 但是作者已经不回答了 看到主页留有您链接 希望可以解惑 已经折腾一晚了😓

**Comment by fanpeace** [comment]
> > > @shine-233 @zonghaofan Traceback (most recent call last): File "train.py", line 4, in from keras.callbacks import LearningRateScheduler, ModelCheckpoint File "D:\Miniconda\lib\site-packages\keras__init__.py", line 21, in from tensorflow.python import tf2 ImportError: cannot import name 'tf2'
> > > 输完训练模型代码就卡在这个tf2这里 求指点
> > 
> > 
> > 没有你说的这行代码啊，这是pytorch没有tf
> 
> https://github.com/zxq2233/n2n-watermark-remove 其实是这个项目的 小白跟着保姆级教程走的 但是作者已经不回答了 看到主页留有您链接 希望可以解惑 已经折腾一晚了sweat

tf不是很熟悉，不过看样子好像是tf版本不对，导致import不了tf2

**Comment by Ceiso1** [comment]
> > > > @shine-233 @zonghaofan Traceback (most recent call last): File "train.py", line 4, in from keras.callbacks import LearningRateScheduler, ModelCheckpoint File "D:\Miniconda\lib\site-packages\keras__init__.py", line 21, in from tensorflow.python import tf2 ImportError: cannot import name 'tf2'
> > > > 输完训练模型代码就卡在这个tf2这里 求指点
> > > 
> > > 
> > > 没有你说的这行代码啊，这是pytorch没有tf
> > 
> > 
> > https://github.com/zxq2233/n2n-watermark-remove 其实是这个项目的 小白跟着保姆级教程走的 但是作者已经不回答了 看到主页留有您链接 希望可以解惑 已经折腾一晚了sweat
> 
> tf不是很熟悉，不过看样子好像是tf版本不对，导致import不了tf2

tf是1.9的 import这里是tf2 我也不知道该怎么弄这里...
原作者项目主页里写着您的这个是他的优化版，但我小白也不会安装使用您的n2n...

**Comment by fanpeace** [comment]
> > > > > @shine-233 @zonghaofan Traceback (most recent call last): File "train.py", line 4, in from keras.callbacks import LearningRateScheduler, ModelCheckpoint File "D:\Miniconda\lib\site-packages\keras__init__.py", line 21, in from tensorflow.python import tf2 ImportError: cannot import name 'tf2'
> > > > > 输完训练模型代码就卡在这个tf2这里 求指点
> > > > 
> > > > 
> > > > 没有你说的这行代码啊，这是pytorch没有tf
> > > 
> > > 
> > > https://github.com/zxq2233/n2n-watermark-remove 其实是这个项目的 小白跟着保姆级教程走的 但是作者已经不回答了 看到主页留有您链接 希望可以解惑 已经折腾一晚了sweat
> > 
> > 
> > tf不是很熟悉，不过看样子好像是tf版本不对，导致import不了tf2
> 
> tf是1.9的 import这里是tf2 我也不知道该怎么弄这里... 原作者项目主页里写着您的这个是他的优化版，但我小白也不会安装使用您的n2n...

小白的话，如果要用这个，建议先去学习一下pytorch

**Comment by Ceiso1** [comment]
> > > > > > @shine-233 @zonghaofan Traceback (most recent call last): File "train.py", line 4, in from keras.callbacks import LearningRateScheduler, ModelCheckpoint File "D:\Miniconda\lib\site-packages\keras__init__.py", line 21, in from tensorflow.python import tf2 ImportError: cannot import name 'tf2'
> > > > > > 输完训练模型代码就卡在这个tf2这里 求指点
> > > > > 
> > > > > 
> > > > > 没有你说的这行代码啊，这是pytorch没有tf
> > > > 
> > > > 
> > > > https://github.com/zxq2233/n2n-watermark-remove 其实是这个项目的 小白跟着保姆级教程走的 但是作者已经不回答了 看到主页留有您链接 希望可以解惑 已经折腾一晚了sweat
> > > 
> > > 
> > > tf不是很熟悉，不过看样子好像是tf版本不对，导致import不了tf2
> > 
> > 
> > tf是1.9的 import这里是tf2 我也不知道该怎么弄这里... 原作者项目主页里写着您的这个是他的优化版，但我小白也不会安装使用您的n2n...
> 
> 小白的话，如果要用这个，建议先去学习一下pytorch

好吧 谢谢了
