### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/red_detection/noise2noise/src/font'

### ISSUE THREAD

**Issue by Bob-jpg** [zonghaofan/noise2noise#6]
![图片](https://user-images.githubusercontent.com/56429665/147731055-7b90133c-4f87-4074-9098-abbb9cde01e6.png)

这个路径代表什么，作者

**Comment by fanpeace** [comment]
存放字体的路径,这里可以换成你自己的字体路径
