### ISSUE TITLE
Mr. zong  could this run on win 10 system? I really need a software remove the watermark instead of  Photoshop. 

### ISSUE THREAD

**Issue by sunrisesr** [zonghaofan/noise2noise#7]
please leave me something so that i can contact you for details

**Comment by zonghaofan** [comment]
yes,but need to retrain on your watermark data.

**Comment by fanpeace** [comment]
> please leave me something so that i can contact you for details

yes,but need to retrain on your watermark data.

**Comment by sunrisesr** [comment]
Hi, thanks your reply. do you mean it can only remove certain type of watermark or any watermark? my wechat ID is: xmsunrise thanks

**Comment by fanpeace** [comment]
> Hi, thanks your reply. do you mean it can only remove certain type of watermark or any watermark? my wechat ID is: xmsunrise thanks

ok
